import { File, User, Department } from "../types";

export const mockFiles: File[] = [
  {
    id: 1,
    filename: "rapport_q1_2024.pdf",
    originalName: "Rapport_Q1_2024.pdf",
    fileType: "pdf",
    fileSize: 2400000,
    filePath: "/uploads/rapport_q1_2024.pdf",
    uploadedBy: 2,
    department: "Comptabilité",
    category: "Rapport",
    description: "Rapport trimestriel Q1 2024",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: 2,
    filename: "manuel_procedures.docx",
    originalName: "Manuel_Procedures.docx",
    fileType: "docx",
    fileSize: 1800000,
    filePath: "/uploads/manuel_procedures.docx",
    uploadedBy: 3,
    department: "Ressources Humaines",
    category: "Manuel",
    description: "Manuel des procédures internes",
    createdAt: new Date("2024-01-08"),
  },
  {
    id: 3,
    filename: "budget_2024.xlsx",
    originalName: "Budget_2024.xlsx",
    fileType: "xlsx",
    fileSize: 3200000,
    filePath: "/uploads/budget_2024.xlsx",
    uploadedBy: 2,
    department: "Comptabilité",
    category: "Budget",
    description: "Budget prévisionnel 2024",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 4,
    filename: "logo_entreprise.png",
    originalName: "Logo_Entreprise.png",
    fileType: "png",
    fileSize: 856000,
    filePath: "/uploads/logo_entreprise.png",
    uploadedBy: 4,
    department: "Marketing",
    category: "Design",
    description: "Logo officiel de l'entreprise",
    createdAt: new Date("2024-01-10"),
  },
];

export const mockUsers: User[] = [
  {
    id: 1,
    username: "john.doe",
    email: "john.doe@archivio.com",
    role: "superuser",
    department: "Administration",
    firstName: "John",
    lastName: "Doe",
    isActive: true,
    lastLogin: new Date(),
  },
  {
    id: 2,
    username: "marie.dubois",
    email: "marie.dubois@archivio.com",
    role: "admin",
    department: "Comptabilité",
    firstName: "Marie",
    lastName: "Dubois",
    isActive: true,
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 3,
    username: "pierre.martin",
    email: "pierre.martin@archivio.com",
    role: "user",
    department: "Ressources Humaines",
    firstName: "Pierre",
    lastName: "Martin",
    isActive: true,
    lastLogin: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];

export const mockDepartments: Department[] = [
  { id: 1, name: "Administration", description: "Administration générale" },
  { id: 2, name: "Comptabilité", description: "Gestion financière" },
  { id: 3, name: "Ressources Humaines", description: "Gestion du personnel" },
  { id: 4, name: "Marketing", description: "Communication et marketing" },
  { id: 5, name: "IT", description: "Informatique" },
];
